sudo: required

dist: xenial

language: cpp

compiler:
  - gcc
  - clang

env:
  - AUDIO_BACKEND="Pulseaudio"
  - AUDIO_BACKEND="Portaudio"
  - AUDIO_BACKEND="Gr-audio"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake qt5-default libqt5svg5-dev libboost-dev libpulse-dev portaudio19-dev liblog4cpp5-dev gnuradio-dev gr-osmosdr gr-fcdproplus

script:
  - mkdir build
  - cd build
  - cmake -DLINUX_AUDIO_BACKEND:STRING=$AUDIO_BACKEND ..
  - make
